application: gu-tickticktick
version: 11
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /tasks/.*
  script: tasks.app
  login: admin
- url: /api/.*
  script: api.app
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on